In [1]:
import torch

In [3]:
a = torch.tensor([[True, False, True], [True, True, False]])
b = torch.tensor([1, 2, 3])
for i in range(a.shape[0]):
    print(b[a[i]], a[i].shape)

tensor([1, 3]) torch.Size([3])
tensor([1, 2]) torch.Size([3])


In [8]:
c = torch.tensor([[1, 2], [3, 4], [5, 6]])
d = torch.tensor([7, 8, 9])
torch.cat((c, d.unsqueeze(1)), dim=1)

tensor([[1, 2, 7],
        [3, 4, 8],
        [5, 6, 9]])