In [1]:
import os

In [4]:
split = 'val'
kitti360Path = "/data/shared_workspace/yuzijian/ws/ISeg3D/data/kitti360/unzip"
outputPath = os.path.join("/data/shared_workspace/yuzijian/ws/ISeg3D/data/kitti360/preprocess", split)
os.makedirs(outputPath, exist_ok=True)
with open(os.path.join(kitti360Path, 'data_3d_semantics', 'train', f'2013_05_28_drive_{split}.txt'), 'r') as f:
    files = f.read().split()

print(files)

['data_3d_semantics/train/2013_05_28_drive_0000_sync/static/0000000372_0000000610.ply', 'data_3d_semantics/train/2013_05_28_drive_0000_sync/static/0000000599_0000000846.ply', 'data_3d_semantics/train/2013_05_28_drive_0000_sync/static/0000000834_0000001286.ply', 'data_3d_semantics/train/2013_05_28_drive_0000_sync/static/0000001270_0000001549.ply', 'data_3d_semantics/train/2013_05_28_drive_0000_sync/static/0000001537_0000001755.ply', 'data_3d_semantics/train/2013_05_28_drive_0000_sync/static/0000001740_0000001991.ply', 'data_3d_semantics/train/2013_05_28_drive_0000_sync/static/0000002695_0000002925.ply', 'data_3d_semantics/train/2013_05_28_drive_0000_sync/static/0000003221_0000003475.ply', 'data_3d_semantics/train/2013_05_28_drive_0000_sync/static/0000003463_0000003724.ply', 'data_3d_semantics/train/2013_05_28_drive_0000_sync/static/0000003711_0000003928.ply', 'data_3d_semantics/train/2013_05_28_drive_0002_sync/static/0000004391_0000004625.ply', 'data_3d_semantics/train/2013_05_28_drive_

In [15]:
os.path.dirname(files[0]).split('/')[-2]

'2013_05_28_drive_0000_sync'

In [10]:
os.path.basename(files[0]).split('.')[0]

'0000000372_0000000610'

In [20]:
import plyfile
import numpy as np
import glob
from helpers.ply import read_ply

In [17]:
files = glob.glob(os.path.join("/data/shared_workspace/yuzijian/ws/ISeg3D/data/kitti360/unzip/data_3d_semantics/test", '*', 'static', '*.ply'))
data_path = files[0]
data_path

'/data/shared_workspace/yuzijian/ws/ISeg3D/data/kitti360/unzip/data_3d_semantics/test/2013_05_28_drive_0018_sync/static/0000003215_0000003513.ply'

In [18]:
f = plyfile.PlyData().read(data_path)
points = np.array([list(x) for x in f.elements[0]])
coords = np.ascontiguousarray(points[:, :3])
colors = np.ascontiguousarray(points[:, 3:6])
coords

array([[3638.0806, 1560.1779,  128.895 ],
       [3643.0215, 1551.145 ,  131.0147],
       [3643.051 , 1551.2428,  131.0168],
       ...,
       [3637.3652, 1562.2391,  130.6731],
       [3637.3164, 1562.336 ,  130.7374],
       [3637.1965, 1562.5867,  130.8099]], dtype=float32)

In [26]:
data = read_ply(data_path)
points = np.vstack((data['x'], data['y'], data['z'])).T
colors = np.vstack((data['red'], data['green'], data['blue'])).T
colors = colors.astype(np.float32)
points

array([[3638.0806, 1560.1779,  128.895 ],
       [3643.0215, 1551.145 ,  131.0147],
       [3643.051 , 1551.2428,  131.0168],
       ...,
       [3637.3652, 1562.2391,  130.6731],
       [3637.3164, 1562.336 ,  130.7374],
       [3637.1965, 1562.5867,  130.8099]], dtype=float32)

In [28]:
data_path = "/data/shared_workspace/yuzijian/ws/ISeg3D/data/kitti360/train/2013_05_28_drive_0000_sync/0000000002_0000000385"
data_dict = {}
assets = os.listdir(data_path)
for asset in assets:
    if not asset.endswith(".npy"):
        continue

    data_dict[asset[:-4]] = np.load(os.path.join(data_path, asset))
data_dict

{'semantic': array([8, 8, 8, ..., 8, 8, 8], dtype=int32),
 'coord': array([[1000.8657, 3820.2976,  116.2225],
        [1000.8753, 3820.3816,  116.193 ],
        [1000.9065, 3820.6013,  116.188 ],
        ...,
        [1001.1812, 3820.5242,  117.0209],
        [1001.1264, 3820.5708,  117.1629],
        [1001.1545, 3820.547 ,  117.3406]], dtype=float32),
 'color': array([[18., 29., 18.],
        [19., 21., 19.],
        [12., 14., 11.],
        ...,
        [13., 17., 14.],
        [12., 14., 12.],
        [19., 17., 17.]], dtype=float32),
 'instance': array([-1, -1, -1, ..., -1, -1, -1], dtype=int32)}

In [30]:
np.unique(data_dict['instance'].reshape([-1]).astype(np.int32))

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81],
      dtype=int32)

In [36]:
os.path.basename(os.path.dirname(data_path))

'2013_05_28_drive_0000_sync'

In [2]:
from helpers.labels import trainId2label

In [4]:
trainId2label[4]

Label(name='fence', id=13, kittiId=8, trainId=4, category='construction', categoryId=2, hasInstances=False, ignoreInEval=False, ignoreInInst=False, color=(190, 153, 153))

In [5]:
trainId2label.keys()

dict_keys([-1, 255, 5, 4, 2, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 3, 1, 0])

In [8]:
{i:trainId2label[i].name for i in trainId2label.keys()}

{-1: 'unlabeled',
 5: 'pole',
 4: 'fence',
 2: 'building',
 18: 'bicycle',
 17: 'motorcycle',
 16: 'train',
 15: 'bus',
 14: 'truck',
 13: 'car',
 12: 'rider',
 11: 'person',
 10: 'sky',
 9: 'terrain',
 8: 'vegetation',
 7: 'traffic sign',
 6: 'traffic light',
 3: 'wall',
 1: 'sidewalk',
 0: 'road'}